### ISSUE TITLE
Create a simple Local database with Expenses table and insert/delete UI

### ISSUE THREAD

**Issue by TomasHubelbauer** [TomasHubelbauer/ExpenseTracker#1]
Following the [Local database](https://msdn.microsoft.com/library/windows/apps/hh202860.aspx) documentation on MSDN, create a Local database for the application with tables `Expenses` and `Currencies` for the sake of playing around with foreign keys/navigation properties in LINQ2SQL.

`Expenses`
- `Id` - The identifier of the expense. Primary key
- `ExpendedDateAndTime` - The date and time the expense was expended.
- `Amount` - The amound expended, in a data format usitable for currency. `Decimal` in the application, to be determined in the database, depending on what Local database has to offer.
- `CurrencyId` - The identifier of the currency. Foreign key.

`Currencies`
- `Id` - The identifier of the currency. Primary key.
- `Code` - The currency code, like *CZK* or *USD*, according to ISO 4217.
- `Name` - The currency name, like *Koruna česká* or *United States dollar*.

# Tasks
- [x] Read up Local database and plan the implementation steps.
- [x] Figure out that Window Phone Silverlight application project is hidden in a plain sight :disappointed:.
- [x] Define th data context for the database proxy in LINQ2SQL.
- [x] Create a helper assembly abstracting away the LINQ2SQL base entity cruft.
- [x] Create application model for `Currency`.
- [x] Create application model for `Expense`.
