### ISSUE TITLE
Consider upgrading to an universal app and using SQLite with ORM

### ISSUE THREAD

**Issue by TomasHubelbauer** [TomasHubelbauer/ExpenseTracker#39]
http://web.archive.org/web/*/http://developer.nokia.com/community/wiki/How_to_use_SQLite_in_Windows_Phone

# Tasks
- [ ] Set up a new project to test out the SQLite + ORM in.
- [ ] Evaluate the complexity involved and the downsides of using third-party database engine.
- [ ] Decide whether or not to upgrade this project.

**Comment by TomasHubelbauer** [comment]
http://blog.tpcware.com/2014/04/universal-app-with-sqlite-part-1/ [1/2]
http://blog.tpcware.com/2014/05/universal-app-with-sqlite-part-2/ [2/2]
http://www.codeproject.com/Articles/826602/Using-SQLite-as-local-database-with-Universal-Apps

**Comment by TomasHubelbauer** [comment]
**https://sqlitepcl.codeplex.com/** Nuget abstracting away the complexity?
