### ISSUE TITLE
Change data context properties to public fields and apply attributes directly on models

### ISSUE THREAD

**Issue by TomasHubelbauer** [TomasHubelbauer/ExpenseTracker#7]
Seems as though the LINQ2SQL runtime requires for the table member to be public fields (:-1:) and also the [`Table`](https://msdn.microsoft.com/en-us/library/system.data.linq.mapping.tableattribute.aspx) attribute is not inherited (:-1: :-1:).

# Tasks
- [x] Change properties to fields on data context and include suppresions for style checks with description.
- [x] Apply attributes directly onto the entities rather than to the base entity class.
- [x] Deploy and debug other mapping-related issues.
