### ISSUE TITLE
Create a new view for expense registration, without autocomplete at this stage

### ISSUE THREAD

**Issue by TomasHubelbauer** [TomasHubelbauer/ExpenseTracker#9]
# Tasks
- [x] Create a view with expense registration controls.
- [x] Add a application bar button leading to that view.
- [x] Create a view model for the expense registration view.
- [x] Implement saving functionality in the view model before proper DAL is established.
